# website settings
website:
  title: ""
  description: "Dave Taylor | Applied economist, Bikepacker and Khachapuri fan"
  image: img/my_image.jpg
  favicon: img/favicon.gif
  open-graph: true
  google-analytics: 
    tracking-id: "G-KV4E3C6HT8"
    anonymize-ip: true
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/name_logo.png
    
    # your sub-pages
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Photos"
        href: photos.qmd
      - text: "Films"
        menu: 
          - href: fuchsia-melancholy-road.qmd
      - text: "CV"
        href: https://research.monash.edu/en/persons/david-taylor-3
    
    # Your social media handles
    right:
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/davetaylor.au
      - text: "{{< iconify fa6-brands x-twitter size=1.1em title='X' >}}"
        href: https://x.com/davetayl_r
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/davetayl-r
      - text: "{{< iconify fa6-brands instagram size=1.1em title='Instagram' >}}"
        href: https://instagram.com/davetayl_r
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/djataylor/
      - text: "{{< iconify bi envelope size=1.1em title='Email' >}}"
        href: "mailto:websitecontact@mail.davetaylor.au"

  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2023-25 Dave Taylor</span>
    center: |
      <span class="faux-block">[{{< fa brands orcid >}} <strong>ORCID</strong>](https://orcid.org/0000-0001-8801-7488)</span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View source at {{< fa brands square-github >}}](https://github.com/davetayl-r/davetaylor-dot-au)</span>

project:
  type: website
  output-dir: docs
  resources:
    - CNAME
  
  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true